import { PokemonType } from './pokemonTypes';

type Weaknesses = {
  [key in PokemonType]?: PokemonType[];
};
type Resistances = {
  [key in PokemonType]?: PokemonType[];
};

type Normal = {
  [key in PokemonType]?: PokemonType[];
};

type Immunities = {
  [key in PokemonType]?: PokemonType[];
};

export class TypeEffectiveness {
  typeWeaknesses: Weaknesses = {
    Normal: ['Fighting'],
    Fire: ['Water', 'Ground', 'Rock'],
    Water: ['Electric', 'Grass'],
    Electric: ['Ground'],
    Grass: ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'],
    Ice: ['Fire', 'Fighting', 'Rock', 'Steel'],
    Fighting: ['Flying', 'Psychic', 'Fairy'],
    Poison: ['Ground', 'Psychic'],
    Ground: ['Water', 'Grass', 'Ice'],
    Flying: ['Electric', 'Ice', 'Rock'],
    Psychic: ['Bug', 'Ghost', 'Dark'],
    Bug: ['Fire', 'Flying', 'Rock'],
    Rock: ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'],
    Ghost: ['Ghost', 'Dark'],
    Dragon: ['Ice', 'Dragon', 'Fairy'],
    Dark: ['Fighting', 'Bug', 'Fairy'],
    Steel: ['Fire', 'Fighting', 'Ground'],
    Fairy: ['Poison', 'Steel'],
  };

  typeResistances: Resistances = {
    Normal: [],
    Fire: ['Fire', 'Grass', 'Ice', 'Steel', 'Fairy'],
    Water: ['Fire', 'Water', 'Ice', 'Steel'],
    Electric: ['Electric', 'Steel'],
    Grass: ['Water', 'Electric', 'Grass', 'Ground'],
    Ice: ['Ice'],
    Fighting: ['Bug', 'Rock', 'Dark'],
    Poison: ['Grass', 'Fighting', 'Poison', 'Bug', 'Fairy'],
    Ground: ['Poison', 'Rock'],
    Flying: ['Grass', 'Fighting', 'Bug'],
    Psychic: ['Fighting', 'Psychic'],
    Bug: ['Grass', 'Fighting', 'Ground'],
    Rock: ['Normal', 'Fire', 'Poison', 'Flying'],
    Ghost: ['Poison', 'Bug'],
    Dragon: ['Fire', 'Water', 'Electric', 'Grass'],
    Dark: ['Ghost', 'Dark'],
    Steel: [
      'Normal',
      'Grass',
      'Ice',
      'Flying',
      'Psychic',
      'Bug',
      'Rock',
      'Dragon',
      'Steel',
      'Fairy',
    ],
    Fairy: ['Fighting', 'Bug', 'Dark'],
  };

  typeImmunities: Immunities = {
    Normal: ['Ghost'],
    Fire: [],
    Water: [],
    Electric: [],
    Grass: [],
    Ice: [],
    Fighting: [],
    Poison: [],
    Ground: ['Electric'],
    Flying: ['Ground'],
    Psychic: [],
    Bug: [],
    Rock: [],
    Ghost: ['Normal', 'Fighting'],
    Dragon: [],
    Dark: ['Psychic'],
    Steel: ['Poison'],
    Fairy: ['Dragon'],
  };

  typeNormals: Normal = {
    Normal: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Poison',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Rock',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Fire: [
      'Normal',
      'Electric',
      'Fighting',
      'Poison',
      'Flying',
      'Psychic',
      'Ghost',
      'Dragon',
      'Dark',
    ],
    Water: [
      'Normal',
      'Fighting',
      'Poison',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Fairy',
    ],
    Electric: [
      'Normal',
      'Fire',
      'Water',
      'Grass',
      'Ice',
      'Fighting',
      'Poison',
      'Psychic',
      'Bug',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Fairy',
    ],
    Grass: [
      'Normal',
      'Fighting',
      'Psychic',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Ice: [
      'Normal',
      'Water',
      'Electric',
      'Grass',
      'Poison',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Ghost',
      'Dragon',
      'Dark',
      'Fairy',
    ],
    Fighting: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Fighting',
      'Poison',
      'Ground',
      'Ghost',
      'Dragon',
      'Steel',
    ],
    Poison: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Ice',
      'Flying',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
    ],
    Ground: [
      'Normal',
      'Fire',
      'Fighting',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Flying: [
      'Normal',
      'Fire',
      'Water',
      'Poison',
      'Flying',
      'Psychic',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Psychic: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Poison',
      'Ground',
      'Flying',
      'Rock',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Bug: [
      'Normal',
      'Water',
      'Electric',
      'Ice',
      'Poison',
      'Psychic',
      'Bug',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    Rock: [
      'Electric',
      'Ice',
      'Psychic',
      'Bug',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Fairy',
    ],
    Ghost: [
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Ground',
      'Flying',
      'Psychic',
      'Rock',
      'Dragon',
      'Steel',
      'Fairy',
    ],
    Dragon: [
      'Normal',
      'Fighting',
      'Poison',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Rock',
      'Ghost',
      'Dark',
      'Steel',
    ],
    Dark: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Poison',
      'Ground',
      'Flying',
      'Rock',
      'Dragon',
      'Steel',
    ],
    Steel: ['Water', 'Electric', 'Ghost', 'Dark'],
    Fairy: [
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Ground',
      'Flying',
      'Psychic',
      'Rock',
      'Ghost',
      'Fairy',
    ],
  };

  getTypeWeaknesses() {
    return this.typeWeaknesses;
  }
  getTypeResistances() {
    return this.typeResistances;
  }
  getTypeImmunities() {
    return this.typeImmunities;
  }
  getTypeNormals() {
    return this.typeNormals;
  }
}
